BLOCKSDS ?= $(BLOCKSDS)
# BLOCKSDS ?= $(WONDERFUL_TOOLCHAIN)/thirdparty/blocksds/core

NAME := simple_example
GAME_TITLE := Simple Example
GAME_SUBTITLE := Built with Nix

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile

